name: build-image

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=build_date::v$(date -u +'%Y%m%d')
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            colachen/caddy2:latest
            colachen/caddy2:${{ steps.prepare.outputs.build_date }}
            colachen/caddy2:v1.0.0

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Test docker image
        run: |
          docker run --rm colachen/caddy2 caddy version